using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SurfBoardProject.Data;
using SurfBoardProject.Models;
using System.Reflection.Metadata.Ecma335;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RentAPI : ControllerBase
    {

        private readonly SurfBoardProjectContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public RentAPI(SurfBoardProjectContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> GetRentals()
        {
            try
            {
                var rentals = await _context.Rental.ToListAsync();
                return Ok(rentals);
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
        }

        [HttpGet("GetRental")]
        public async Task<IActionResult> GetRental([FromQuery] string userId)
        {
            try
            {
                // Use the userId parameter to filter rentals
                var rentals = await _context.Rental
                    .Where(r => r.Customers.Any(c => c.UserId == userId))
                    .Include(r => r.Boards)
                    .Include(r => r.Customers)
                    .ToListAsync();
                var options = new JsonSerializerOptions
                {
                    ReferenceHandler = ReferenceHandler.Preserve,
                };

                var jsonSerialized = System.Text.Json.JsonSerializer.Serialize(rentals, options);


                return Ok(jsonSerialized);
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
        }




        [HttpPost]
        public async Task<IActionResult> CreateRental(int id, [FromBody] RentalCustomer rentalCustomer)
        {
            var userId = _userManager.GetUserId(User);
            rentalCustomer.Customer.UserId = userId;

            var boardToUpdate = await _context.BoardModel.FirstOrDefaultAsync(m => m.Id == id);

            if (boardToUpdate != null)
            {
                if (boardToUpdate.IsAvailable == 0)
                {
                    ModelState.Remove("Rental.RowVersion");
                    if (ModelState.IsValid)
                    {
                        // Proceed with booking
                        boardToUpdate.IsAvailable = 1;

                        var newCustomer = new Customer
                        {
                            UserId = userId,
                            Name = rentalCustomer.Customer.Name,
                            LastName = rentalCustomer.Customer.LastName,
                            Email = rentalCustomer.Customer.Email,
                            PhoneNumber = rentalCustomer.Customer.PhoneNumber,
                            Rentals = new List<Rental>
                            {
                                new Rental
                                {
                                    Start = rentalCustomer.Rental.Start,
                                    End = rentalCustomer.Rental.End,
                                    Price = rentalCustomer.Rental.Price,
                                    // RowVersion will be generated by the database
                                    Boards = new List<BoardModel> { boardToUpdate }
                                }
                            }
                        };

                        _context.Customer.Add(newCustomer);

                        // SaveChangesAsync will handle concurrency conflicts
                        await _context.SaveChangesAsync();

                        return CreatedAtAction(nameof(GetRental), new { id = newCustomer.Rentals.First().RentalId }, newCustomer.Rentals.First());
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "The chosen board has already been booked by another user, please choose another board");
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Board not found.");
            }

            return BadRequest(ModelState);
        }

        // Other actions...

        // DELETE: api/Rentals/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteRental(int id)
        {
            var rental = await _context.Rental.FindAsync(id);
            if (rental == null)
            {
                return NotFound();
            }

            _context.Rental.Remove(rental);
            await _context.SaveChangesAsync();

            return NoContent();
        }
    }
}